spring:
  profiles:
    active: dev
mybatis:
  mapper-locations: classpath*:com/mall/order/dal/persistence/*Mapper.xml"
  type-aliases-package: com.mall.order.dal.entitys
mq:
  nameserver:
    addr: 127.0.0.1:9876
  topicname: order
  topicname2: promo_order

