spring:
  application:
    name: gateway
  profiles:
    active: dev
  mvc:
      static-path-pattern: /image/**
  resources:
        static-locations: D:\王道\spring框架\项目3\project4\project4\static\images\
  redisson:
        address: 127.0.0.1:6379
        database: 0
        timeout: 3000
        pool:
          max-active: 20
          max-idle: 10
          max-wait: 3000
          min-idle: 4
server:
  port: 8080
